build_image: shippableimages/ubuntu1404_base
cache: true
before_install:
  - shippable_retry sudo apt-get -y -q update
install:
  - shippable_retry sudo apt-get -y -q install --no-install-recommends qtbase5-private-dev libqt5webkit5-dev libarchive-dev
script:
  - qmake
  - make
